# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DA53szQHpUWDfJLYmd-wJ85QesPUokpE
"""

import torch
from torch.autograd import Function
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torchvision.datasets import ImageFolder
from torchvision.transforms import Compose, Resize, ToTensor, Normalize
from torch.utils.data import DataLoader

device = torch.accelerator.current_accelerator() if torch.accelerator.is_available() else 'cpu'

class CustomConv2DFunction(Function) :

  @staticmethod
  def forward(ctx, input, weight, bias) :
    print("Inside the forward method")
    print(f"Input Shape: {input.shape}")
    print(f"Weight Shate : {weight.shape}")
    print(f"Bias Shape: {bias.shape}")
    ctx.save_for_backward(input, weight, bias)

    batch, in_channels, input_height, input_width = input.shape
    out_channels, _, kernel_height, kernel_width = weight.shape

    output_height = input_height - kernel_height + 1
    output_width = input_width - kernel_width + 1

    output = torch.zeros(batch, out_channels, output_height, output_width, device=input.device, dtype=input.dtype)
    for b in range(batch):
      for channel in range(out_channels):
        for i in range(output_height):
          for j in range(output_width):

            region = input[b, :, i:i+kernel_height, j:j+kernel_width]
            output[b, channel, i, j] = torch.sum(region * weight[channel]) + bias[channel]
      print(f"Output : {output}")
    return output

  @staticmethod
  def backward(ctx, output_grad):

    print(f"Output_gradient : {output_grad}")
    input, weight, bias = ctx.saved_tensors

    batch, in_channels, input_height, input_width = input.shape
    out_channels, _, kernel_height, kernel_width = weight.shape

    _, _, output_height, output_width = output_grad.shape

    input_grad = torch.zeros_like(input, device=input.device, dtype=input.dtype)
    weight_grad = torch.zeros_like(weight, device=weight.device, dtype=weight.dtype)
    bias_grad = torch.zeros_like(bias, dtype=bias.dtype, device=bias.device)

    for b in range(batch):
        for channel in range(out_channels):
            for i in range(output_height):
                for j in range(output_width):

                    region = input[
                        b,
                        :,
                        i:i + kernel_height,
                        j:j + kernel_width
                    ]

                    grad = output_grad[b, channel, i, j]
                    weight_grad[channel] += region * grad
                    input_grad[
                        b,
                        :,
                        i:i + kernel_height,
                        j:j + kernel_width
                    ] += weight[channel] * grad

                    bias_grad[channel] += grad
                    print(f"Grad : {grad}")
                    print(f"Bias : {bias}")

    return input_grad, weight_grad, bias_grad

class CustomConv2D(nn.Module) :
  def __init__(self, in_channels, out_channels, kernel_size) :
    super(CustomConv2D, self).__init__()
    self.kernels = nn.Parameter(torch.empty(out_channels, in_channels, kernel_size, kernel_size, device=device, dtype=torch.float))
    self.bias = nn.Parameter(torch.zeros(out_channels, device=device, dtype=torch.float))

  def forward(self, input) :
    return CustomConv2DFunction.apply(input, self.kernels, self.bias)

class NeuralNet(nn.Module) :

  def __init__(self):
    super(NeuralNet, self).__init__()

    self.conv1 = CustomConv2D(3, 32, 3)
    self.conv2 = CustomConv2D(32, 64, 3)
    self.conv3 = CustomConv2D(64, 128, 3)
    self.conv4 = CustomConv2D(128, 256, 3)
    self.conv5 = CustomConv2D(256, 512, 3)
    self.pool = nn.MaxPool2d(kernel_size=2, stride=2)

    self.fc1 = nn.Linear(6*6*512,1024)
    self.fc2 = nn.Linear(1024, 64)
    self.fc3 = nn.Linear(64, 10)
    self.flatten = nn.Flatten(start_dim=1)

  def forward(self, x) :
    x = self.pool(F.relu(self.conv1(x)))
    x = self.pool(F.relu(self.conv2(x)))
    x = self.pool(F.relu(self.conv3(x)))
    x = self.pool(F.relu(self.conv4(x)))
    x = self.pool(F.relu(self.conv5(x)))

    x = self.flatten(x)
    x = F.relu(self.fc1(x))
    x = F.relu(self.fc2(x))
    x = self.fc3(x)
    return x

model = NeuralNet().to(device)

optimizer = optim.Adam(model.parameters(), lr=0.01)
criterion = nn.CrossEntropyLoss()
print(model.parameters)

transform = Compose([
    Resize((256,256)),
    ToTensor(),
    Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))
])

train_data_dir = "./drive/MyDrive/tomato/train"
train_data = ImageFolder(train_data_dir, transform=transform)

test_data_dir = "./drive/MyDrive/tomato/val"
test_data = ImageFolder(test_data_dir, transform=transform)

test_loader = DataLoader(test_data, batch_size=32, shuffle=False)
train_loader = DataLoader(train_data, batch_size=32, shuffle=True)

image, label = train_data[0]
print(image.shape)

for epoch in range(50) :

  print(f"Epoch : {epoch} ")
  running_loss = 0.0
  for i, data in enumerate(train_loader):
    images, labels = data
    images, labels = images.to(device), labels.to(device)

    optimizer.zero_grad()

    outputs = model(images)
    loss = criterion(outputs,labels)

    print(f"Loss : {loss}")

    loss.backward()
    optimizer.step()

    running_loss += loss.item()

  print(f"Running Loss : {running_loss/len(train_loader)}")