# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ueh0X6Xe7g4VjXfTKibcIW1ZM1hXIVDy
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision.transforms import Compose, Resize, ToTensor, Normalize
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.datasets import ImageFolder
import torch.nn.functional as F

device = torch.accelerator.current_accelerator() if torch.accelerator.is_available() else 'cpu'
print(device)

class CNN(nn.Module):
    def __init__(self, num_classes=10):
        super().__init__()

        self.features = nn.Sequential(
            nn.Conv2d(
                in_channels=3,
                out_channels=32,
                kernel_size=3,
            ),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2),

            # Block 2
            nn.Conv2d(
                in_channels=32,
                out_channels=64,
                kernel_size=3,
            ),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2),

            # Block 3
            nn.Conv2d(
                in_channels=64,
                out_channels=128,
                kernel_size=3,
            ),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2),

            # Block 4
            nn.Conv2d(
                in_channels=128,
                out_channels=256,
                kernel_size=3,
            ),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2),

            # Block 5
            nn.Conv2d(
                in_channels=256,
                out_channels=512,
                kernel_size=3,
            ),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2)
        )

        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear(512*6*6, 1024),  # For 32x32 input images
            nn.ReLU(),
            nn.Dropout(0.5),
            nn.Linear(1024, 64),
            nn.ReLU(),
            nn.Dropout(0.5),
            nn.Linear(64, num_classes)
        )

    def forward(self, x):
        x = self.features(x)
        x = self.classifier(x)
        return x

transform = Compose([
    Resize((256,256)),
    ToTensor(),
    Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))
])

train_data_dir = "./drive/MyDrive/tomato/train"
train_data = ImageFolder(train_data_dir, transform=transform)

test_data_dir = "./drive/MyDrive/tomato/val"
test_data = ImageFolder(test_data_dir, transform=transform)

print(train_data.classes)
image , label = train_data[0]
print(image.shape, train_data.classes[label])

test_loader = DataLoader(test_data, batch_size=32, shuffle=False)
train_loader = DataLoader(train_data, batch_size=32, shuffle=True)

model = CNN().to(device)
optimizer = optim.Adam(model.parameters(), lr=0.001)
print(model.parameters)
criterion = nn.CrossEntropyLoss()

for epoch in range(50) :

  print(f"Epoch : {epoch} ")
  running_loss = 0.0
  for i, data in enumerate(train_loader):
    images, labels = data
    images, labels = images.to(device), labels.to(device)

    optimizer.zero_grad()

    outputs = model(images)
    loss = criterion(outputs,labels)

    loss.backward()
    optimizer.step()

    running_loss += loss.item()

  print(f"Running Loss : {running_loss/len(train_loader)}")

torch.save(model, 'tomato.pth')
torch.save(model.state_dict(), 'tomato_state_dict.pth')

tomato_classifier = torch.load('tomato.pth', weights_only=False)
tomato_classifier.to(device)
tomato_classifier.eval()

tomato_classifier.eval()

all_preds = []
all_labels = []

with torch.no_grad():
    for images, labels in test_loader:
        images = images.to(device)
        labels = labels.to(device)

        outputs = tomato_classifier(images)
        _, predicted = torch.max(outputs, 1)

        all_preds.extend(predicted.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report
import matplotlib.pyplot as plt

# ---------------------------
# CONFUSION MATRIX
# ---------------------------
cm = confusion_matrix(all_labels, all_preds)

disp = ConfusionMatrixDisplay(confusion_matrix=cm)
fig, ax = plt.subplots(figsize=(8, 6))
disp.plot(cmap="Blues", ax=ax, values_format="d")
plt.title("Confusion Matrix")
plt.show()

# Save image for report
plt.savefig("confusion_matrix.png", dpi=300, bbox_inches="tight")


# ---------------------------
# METRICS
# ---------------------------
accuracy = accuracy_score(all_labels, all_preds)
precision = precision_score(all_labels, all_preds, average="weighted")
recall = recall_score(all_labels, all_preds, average="weighted")
f1 = f1_score(all_labels, all_preds, average="weighted")

print("Accuracy  :", accuracy)
print("Precision :", precision)
print("Recall    :", recall)
print("F1 Score  :", f1)


# ---------------------------
# FULL CLASSIFICATION REPORT
# ---------------------------
print("\nClassification Report:\n")
print(classification_report(all_labels, all_preds))

from PIL import Image
random_image = Image.open("./dog.jpeg")
random_image = transform(random_image).unsqueeze(0).to(device)
_, prediction = torch.max(tomato_classifier(random_image), 1)
print(train_data.classes[prediction.item()])